sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=sample/**,out/**,coverage/**,node_modules/**,**/*.test.ts,src/__mocks__/**,src/__test_helpers__/**,**/*.groovy
sonar.inclusions=**/*.ts